//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportingApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TestDBEntities : DbContext
    {
        public TestDBEntities()
            : base("name=TestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Publisher> Publishers { get; set; }
        public virtual DbSet<tbl_Student> tbl_Student { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    
        public virtual ObjectResult<sp_getBookNPublisher_Result> sp_getBookNPublisher()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getBookNPublisher_Result>("sp_getBookNPublisher");
        }

        public System.Data.Entity.DbSet<reportingApp.Models.sp_getBookNPublisher_Result> sp_getBookNPublisher_Result { get; set; }
    }
}
